name: Production deploy to Nectar
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Production deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NECTAR_IP }}
          username: ${{ secrets.NECTAR_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd assure-app/
            git pull origin deploy
            source ~/.venv/assure-app/bin/activate
            pip install -r requirements.txt
            cp -r /home/$USER/assure-test/assets/. /home/$USER/assure-app/assets/
            sudo systemctl restart assure-app.service
